# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
